# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Pages-Apache-I18N
version:      0.01
version_from: lib/Sledge/Pages/Apache/I18N.pm
installdirs:  site
requires:
    Apache::Request::I18N:         0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
